name: Build and Test Razor App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can use windows-latest or macos-latest if preferred

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'  # Or any version your app uses
    - name: Restore dependencies
      run: dotnet restore  # Restore NuGet dependencies

    # - name: Build the application
    #   run: dotnet build --configuration Release  # Build the app

    # - name: Run tests
    #   run: dotnet test RAZOR2/Testing --configuration Release --no-build  # Specify the path to your test project

    # - name: Publish the app
    #   run: dotnet publish --configuration Release --output ./publish  # Publish the app for deployment (if needed)
